const ACTION_TOGGLE_FILTER = 'ACTION_TOGGLE_FILTER';
const ACTION_SELECT_PROJECT = 'ACTION_SELECT_PROJECT';

const MQ_NARROW = '(min-width: 415px)';

export default Object.freeze({
    ACTION_TOGGLE_FILTER,
    ACTION_SELECT_PROJECT,
    MQ_NARROW
});
