const ACTION_TOGGLE_FILTER = 'ACTION_TOGGLE_FILTER';
const ACTION_SELECT_PROJECT = 'ACTION_SELECT_PROJECT';
const ACTION_SET_PATH = 'ACTION_SET_PATH';
const ACTION_SET_MOUNTED = 'ACTION_SET_MOUNTED';

export default Object.freeze({
    ACTION_TOGGLE_FILTER,
    ACTION_SELECT_PROJECT,
    ACTION_SET_PATH,
    ACTION_SET_MOUNTED
});
